### ISSUE TITLE
solution for the MIRROR effect

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#154]
on parle ici du phénomène des pattes de Maritime.
par exemple. because we have walnut and natural. if we have only 1 maritime 3-seater in tweed grey in stock, we need to put 1 in stock for walnut and 1 in stock for natural, but we only have 1 for real...

:)

**Comment by minitachinita** [comment]
c'est un projet qu'on aimerait régler cette semaine! :)
the MIRROR EFFECT

on pourra en discuter mercredi si tu as des questions.
thanks!

**Comment by AKRFranko** [comment]
So far I've spend around 16 hours on this and the proposed solution doesnt work. I have also tried a few other solutions to no avail. The one I have right now is bad because it slows down the website drastically. 

I need to rethink the problem and find maybe a workaround that resolves the real issue without adding too much complexity to the website.

**Comment by AKRFranko** [comment]
Foudn a "solution"
